/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Addenda12
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-23T19:59:31.531Z[GMT]")
public class Addenda12 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("typeCode")
  private String typeCode = null;

  @SerializedName("originatorCityStateProvince")
  private String originatorCityStateProvince = null;

  @SerializedName("originatorCountryPostalCode")
  private String originatorCountryPostalCode = null;

  @SerializedName("entryDetailSequenceNumber")
  private BigDecimal entryDetailSequenceNumber = null;

  public Addenda12 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Client-defined string used as a reference to this record.
   * @return id
  **/
  @Schema(example = "5ca8d25a", description = "Client-defined string used as a reference to this record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Addenda12 typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

   /**
   * 12 - NACHA regulations
   * @return typeCode
  **/
  @Schema(example = "12", required = true, description = "12 - NACHA regulations")
  public String getTypeCode() {
    return typeCode;
  }

  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public Addenda12 originatorCityStateProvince(String originatorCityStateProvince) {
    this.originatorCityStateProvince = originatorCityStateProvince;
    return this;
  }

   /**
   * Originator City &amp; State / Province Data elements City and State / Province  should be separated with an asterisk (*) as a delimiter and the field should end with a backslash (\\\\). 
   * @return originatorCityStateProvince
  **/
  @Schema(example = "San Francisco*CA\\ ", required = true, description = "Originator City & State / Province Data elements City and State / Province  should be separated with an asterisk (*) as a delimiter and the field should end with a backslash (\\\\). ")
  public String getOriginatorCityStateProvince() {
    return originatorCityStateProvince;
  }

  public void setOriginatorCityStateProvince(String originatorCityStateProvince) {
    this.originatorCityStateProvince = originatorCityStateProvince;
  }

  public Addenda12 originatorCountryPostalCode(String originatorCountryPostalCode) {
    this.originatorCountryPostalCode = originatorCountryPostalCode;
    return this;
  }

   /**
   * Originator Country &amp; Postal Code Data elements must be separated by an asterisk (*) and must end with a backslash (\\\\). 
   * @return originatorCountryPostalCode
  **/
  @Schema(example = "US*10036\\ ", required = true, description = "Originator Country & Postal Code Data elements must be separated by an asterisk (*) and must end with a backslash (\\\\). ")
  public String getOriginatorCountryPostalCode() {
    return originatorCountryPostalCode;
  }

  public void setOriginatorCountryPostalCode(String originatorCountryPostalCode) {
    this.originatorCountryPostalCode = originatorCountryPostalCode;
  }

  public Addenda12 entryDetailSequenceNumber(BigDecimal entryDetailSequenceNumber) {
    this.entryDetailSequenceNumber = entryDetailSequenceNumber;
    return this;
  }

   /**
   * EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record&#x27;s trace number. This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record. 
   * @return entryDetailSequenceNumber
  **/
  @Schema(example = "2618117", required = true, description = "EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record's trace number. This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record. ")
  public BigDecimal getEntryDetailSequenceNumber() {
    return entryDetailSequenceNumber;
  }

  public void setEntryDetailSequenceNumber(BigDecimal entryDetailSequenceNumber) {
    this.entryDetailSequenceNumber = entryDetailSequenceNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Addenda12 addenda12 = (Addenda12) o;
    return Objects.equals(this.id, addenda12.id) &&
        Objects.equals(this.typeCode, addenda12.typeCode) &&
        Objects.equals(this.originatorCityStateProvince, addenda12.originatorCityStateProvince) &&
        Objects.equals(this.originatorCountryPostalCode, addenda12.originatorCountryPostalCode) &&
        Objects.equals(this.entryDetailSequenceNumber, addenda12.entryDetailSequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, typeCode, originatorCityStateProvince, originatorCountryPostalCode, entryDetailSequenceNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Addenda12 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    originatorCityStateProvince: ").append(toIndentedString(originatorCityStateProvince)).append("\n");
    sb.append("    originatorCountryPostalCode: ").append(toIndentedString(originatorCountryPostalCode)).append("\n");
    sb.append("    entryDetailSequenceNumber: ").append(toIndentedString(entryDetailSequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
