/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Addenda16
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-23T19:59:31.531Z[GMT]")
public class Addenda16 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("typeCode")
  private String typeCode = null;

  @SerializedName("receiverCityStateProvince")
  private String receiverCityStateProvince = null;

  @SerializedName("receiverCountryPostalCode")
  private String receiverCountryPostalCode = null;

  @SerializedName("entryDetailSequenceNumber")
  private BigDecimal entryDetailSequenceNumber = null;

  public Addenda16 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Client-defined string used as a reference to this record.
   * @return id
  **/
  @Schema(example = "5ca8d25a", description = "Client-defined string used as a reference to this record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Addenda16 typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

   /**
   * 16 - NACHA regulations
   * @return typeCode
  **/
  @Schema(example = "16", required = true, description = "16 - NACHA regulations")
  public String getTypeCode() {
    return typeCode;
  }

  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public Addenda16 receiverCityStateProvince(String receiverCityStateProvince) {
    this.receiverCityStateProvince = receiverCityStateProvince;
    return this;
  }

   /**
   * Receiver City &amp; State / Province Data elements City and State / Province  should be separated with an asterisk (*) as a delimiter and the field should end with a backslash (\\\\). 
   * @return receiverCityStateProvince
  **/
  @Schema(example = "San Francisco*CA\\ ", required = true, description = "Receiver City & State / Province Data elements City and State / Province  should be separated with an asterisk (*) as a delimiter and the field should end with a backslash (\\\\). ")
  public String getReceiverCityStateProvince() {
    return receiverCityStateProvince;
  }

  public void setReceiverCityStateProvince(String receiverCityStateProvince) {
    this.receiverCityStateProvince = receiverCityStateProvince;
  }

  public Addenda16 receiverCountryPostalCode(String receiverCountryPostalCode) {
    this.receiverCountryPostalCode = receiverCountryPostalCode;
    return this;
  }

   /**
   * Receiver Country &amp; Postal Code Data elements must be separated by an asterisk (*) and must end with a backslash (\\\\). 
   * @return receiverCountryPostalCode
  **/
  @Schema(example = "US*10036\\ ", required = true, description = "Receiver Country & Postal Code Data elements must be separated by an asterisk (*) and must end with a backslash (\\\\). ")
  public String getReceiverCountryPostalCode() {
    return receiverCountryPostalCode;
  }

  public void setReceiverCountryPostalCode(String receiverCountryPostalCode) {
    this.receiverCountryPostalCode = receiverCountryPostalCode;
  }

  public Addenda16 entryDetailSequenceNumber(BigDecimal entryDetailSequenceNumber) {
    this.entryDetailSequenceNumber = entryDetailSequenceNumber;
    return this;
  }

   /**
   * EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record&#x27;s trace number. This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record. 
   * @return entryDetailSequenceNumber
  **/
  @Schema(example = "2618117", required = true, description = "EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record's trace number. This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record. ")
  public BigDecimal getEntryDetailSequenceNumber() {
    return entryDetailSequenceNumber;
  }

  public void setEntryDetailSequenceNumber(BigDecimal entryDetailSequenceNumber) {
    this.entryDetailSequenceNumber = entryDetailSequenceNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Addenda16 addenda16 = (Addenda16) o;
    return Objects.equals(this.id, addenda16.id) &&
        Objects.equals(this.typeCode, addenda16.typeCode) &&
        Objects.equals(this.receiverCityStateProvince, addenda16.receiverCityStateProvince) &&
        Objects.equals(this.receiverCountryPostalCode, addenda16.receiverCountryPostalCode) &&
        Objects.equals(this.entryDetailSequenceNumber, addenda16.entryDetailSequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, typeCode, receiverCityStateProvince, receiverCountryPostalCode, entryDetailSequenceNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Addenda16 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    receiverCityStateProvince: ").append(toIndentedString(receiverCityStateProvince)).append("\n");
    sb.append("    receiverCountryPostalCode: ").append(toIndentedString(receiverCountryPostalCode)).append("\n");
    sb.append("    entryDetailSequenceNumber: ").append(toIndentedString(entryDetailSequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
