/*
 * ACH API
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing, and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SegmentedFiles
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-23T19:59:31.531Z[GMT]")
public class SegmentedFiles {
  @SerializedName("creditFileID")
  private String creditFileID = null;

  @SerializedName("debitFileID")
  private String debitFileID = null;

  public SegmentedFiles creditFileID(String creditFileID) {
    this.creditFileID = creditFileID;
    return this;
  }

   /**
   * File ID
   * @return creditFileID
  **/
  @Schema(example = "058960d8", description = "File ID")
  public String getCreditFileID() {
    return creditFileID;
  }

  public void setCreditFileID(String creditFileID) {
    this.creditFileID = creditFileID;
  }

  public SegmentedFiles debitFileID(String debitFileID) {
    this.debitFileID = debitFileID;
    return this;
  }

   /**
   * File ID
   * @return debitFileID
  **/
  @Schema(example = "3cac5447", description = "File ID")
  public String getDebitFileID() {
    return debitFileID;
  }

  public void setDebitFileID(String debitFileID) {
    this.debitFileID = debitFileID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentedFiles segmentedFiles = (SegmentedFiles) o;
    return Objects.equals(this.creditFileID, segmentedFiles.creditFileID) &&
        Objects.equals(this.debitFileID, segmentedFiles.debitFileID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditFileID, debitFileID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentedFiles {\n");
    
    sb.append("    creditFileID: ").append(toIndentedString(creditFileID)).append("\n");
    sb.append("    debitFileID: ").append(toIndentedString(debitFileID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
